import AppIntents
import Foundation
import SpacebarCore

// Shortcuts actions. Their metadata is generated by scripts/build-app.sh (appintentsmetadataprocessor),
// since SwiftPM doesn't do that step itself.

struct FreeUpSpaceIntent: AppIntent {
    static var title: LocalizedStringResource = "Free Up Space"
    static var description = IntentDescription(
        "Removes caches and logs nobody used recently: the same safe clean as Spacebar's automatic cleaning. Your Dry Run setting and Exclusions apply.")

    @Parameter(title: "Dry Run", description: "Only work out how much would be freed.", default: false)
    var dryRun: Bool

    static var parameterSummary: some ParameterSummary {
        Summary("Free up space (dry run: \(\.$dryRun))")
    }

    func perform() async throws -> some IntentResult & ReturnsValue<Int> & ProvidesDialog {
        let requested = dryRun
        let result = await Task.detached(priority: .userInitiated) { () -> (freed: Int64, trashed: Int64, dryRun: Bool) in
            let settings = Headless.Settings.current()
            let plan = Headless.plan(Headless.scan(Headless.safeCategories, settings: settings), settings: settings)
            let report = Headless.clean(plan, dryRun: requested || settings.dryRun)
            return (report.deletedBytes, report.trashedBytes, report.dryRun)
        }.value
        let freed = ByteFormat.string(result.freed)
        let dialog: String
        if result.dryRun {
            dialog = result.freed > 0 ? String(localized: "Spacebar would free \(freed) (dry run, nothing was removed).")
                : String(localized: "Nothing to clean right now.")
        } else {
            dialog = result.freed > 0 ? String(localized: "Freed \(freed).") : String(localized: "Nothing to clean right now.")
        }
        return .result(value: Int(result.freed), dialog: IntentDialog(stringLiteral: dialog))
    }
}

struct AvailableSpaceIntent: AppIntent {
    static var title: LocalizedStringResource = "Get Available Space"
    static var description = IntentDescription("Returns the bytes available on your startup disk, including space macOS can free on its own.")

    func perform() async throws -> some IntentResult & ReturnsValue<Int> & ProvidesDialog {
        guard let space = VolumeSpace.home() else {
            return .result(value: 0, dialog: IntentDialog(stringLiteral: String(localized: "Couldn't read the startup disk's size.")))
        }
        return .result(value: Int(space.available),
                       dialog: IntentDialog(stringLiteral: String(localized: "\(ByteFormat.string(space.available)) available of \(ByteFormat.string(space.total)).")))
    }
}

struct ShowFolderIntent: AppIntent {
    static var title: LocalizedStringResource = "Show Folder in Spacebar"
    static var description = IntentDescription("Opens a folder in Space Explorer to see what takes up space in it.")
    static var openAppWhenRun = true

    @Parameter(title: "Folder", supportedTypeIdentifiers: ["public.folder"])
    var folder: IntentFile

    static var parameterSummary: some ParameterSummary {
        Summary("Show \(\.$folder) in Spacebar")
    }

    @MainActor
    func perform() async throws -> some IntentResult {
        guard let url = folder.fileURL, let link = FinderIntegration.showURL(for: url),
              let target = FinderIntegration.folder(from: link) else {
            throw $folder.needsValueError(IntentDialog(stringLiteral: String(localized: "Choose a folder.")))
        }
        FinderIntegration.request(target)
        return .result()
    }
}

struct SpacebarShortcuts: AppShortcutsProvider {
    static var appShortcuts: [AppShortcut] {
        AppShortcut(intent: FreeUpSpaceIntent(), phrases: [
            "Free up space with \(.applicationName)",
            "Clean up my Mac with \(.applicationName)",
        ])
        AppShortcut(intent: AvailableSpaceIntent(), phrases: [
            "How much space is free in \(.applicationName)",
        ])
    }
}
